name: angel3_orm_service
version: 7.0.0
description: Service implementation that wraps over Angel3 ORM Query classes.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_service
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_framework: ^7.0.0
  angel3_orm: ^7.0.0
  postgres: ^2.4.0
  optional: ^6.0.0
dev_dependencies:
  angel3_migration: ^7.0.0
  angel3_migration_runner: ^7.0.0
  angel3_orm_generator: ^7.0.0
  angel3_orm_postgres: ^7.0.0
  angel3_serialize: ^7.0.0
  build_runner: ^2.0.4
  logging: ^1.0.1
  test: ^1.21.0
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../../container/angel_container
#   angel3_framework:
#     path: ../../framework
#   angel3_http_exception:
#     path: ../../http_exception
#   angel3_model:
#     path: ../../model
#   angel3_route:
#     path: ../../route
#   angel3_mock_request:
#     path: ../../mock_request
#   angel3_serialize:
#     path: ../../serialize/angel_serialize
#   angel3_serialize_generator:
#     path: ../../serialize/angel_serialize_generator
#   angel3_orm_test:
#     path: ../angel_orm_test
#   angel3_orm:
#     path: ../angel_orm
#   angel3_orm_generator:
#     path: ../angel_orm_generator
#   angel3_orm_postgres:
#     path: ../angel_orm_postgres
#   angel3_migration:
#     path: ../angel_migration
#   angel3_migration_runner:
#     path: ../angel_migration_runner
