name: angel3_container_generator
version: 7.1.0-beta.1
description: Codegen support for using pkg:reflectable with pkg:angel3_container.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/container/angel_container_generator
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  angel3_container: ^7.1.0-beta.1
  reflectable: ^4.0.2
dev_dependencies:
  build_runner: ^2.3.0
  build_test: ^2.1.3
  test: ^1.24.0
  lints: ^2.0.0
#dependency_overrides:
#  angel3_container:
#    path: ../angel_container
