name: angel3_migration_runner
version: 7.1.0
description: Command-line based database migration runner for Angel3's ORM.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_migration_runner
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_migration: ^7.0.0
  angel3_orm: ^7.0.0
  args: ^2.1.0
  charcode: ^1.3.0
  postgres: ^2.6.0
  mysql_client: ^0.0.26
  mysql1: ^0.20.0
  logging: ^1.1.0
dev_dependencies:
  lints: ^2.0.0
# dependency_overrides:
#    angel3_orm:
#      path: ../angel_orm
#    angel3_migration:
#      path: ../angel_migration
