name: angel3_serialize
version: 8.0.0
description: Static annotations powering Angel3 model serialization. Combine with angel3_serialize_generator for flexible modeling.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/serialize/angel_serialize
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_model: ^8.0.0
  collection: ^1.17.0
  meta: ^1.9.0
  quiver: ^3.2.0
dev_dependencies:
  lints: ^2.1.0
# dependency_overrides:
#   angel3_model:
#     path: ../../model
  
