name: jael3_language_server
version: 7.0.0
description: Language Server Protocol implementation for the Jael templating engine.
homepage: https://github.com/angel-dart/vscode
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.1.1
#  dart_language_server: ^0.1.16
  file: ^6.1.2
  io: ^1.0.0
  jael3: ^7.0.0
  jael3_preprocessor: ^7.0.0
  json_rpc_2: ^3.0.1
  logging: ^1.0.1
  path: ^1.8.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0
  belatuk_symbol_table: ^4.0.0
  lints: ^2.0.0
executables:
  jael3_language_server: jael3_language_server
dependency_overrides:
  jael3:
    path: ../jael
  jael3_preprocessor:
    path: ../jael_preprocessor
