name: angel3_orm_postgres
version: 7.1.0-beta.1
description: PostgreSQL support for Angel3 ORM. Includes functionality for querying and transactions.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_postgres
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  angel3_orm: ^7.0.0
  logging: ^1.1.0
  pool: ^1.5.0
  postgres: ^2.6.1
  postgres_pool: ^2.1.6
dev_dependencies:
  belatuk_pretty_logging: ^5.0.0
  angel3_orm_generator: ^7.1.0-beta.1
  angel3_orm_test: ^7.2.0-beta.1
  test: ^1.24.0
  lints: ^2.0.0
dependency_overrides:
#   angel3_serialize:
#      path: ../../serialize/angel_serialize
#   angel3_model:
#     path: ../../model
  angel3_orm_test:
    path: ../angel_orm_test
  angel3_orm_genrator:
    path: ../angel_orm_generator
#   angel3_orm:
#      path: ../angel_orm
#   angel3_migration:
#      path: ../angel_migration
