name: jael3_web
version: 7.1.1
description: Experimental virtual DOM/SPA engine built on Jael3. Supports SSR.
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  analyzer: ^5.0.0
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  file: ^6.1.4
  path: ^1.8.2
  jael3: ^7.0.0
  jael3_preprocessor: ^7.0.0
  source_gen: ^1.0.2
dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  lints: ^2.0.0
dependency_overrides:
  jael3:
    path: ../jael
  jael3_preprocessor:
    path: ../jael_preprocessor
