builders:
  angel3_orm:
    import: "package:angel3_orm_generator/angel3_orm_generator.dart"
    builder_factories:
      - migrationBuilder
      - ormBuilder
    auto_apply: root_package
    build_to: source
    build_extensions: 
      .dart":
        - ".angel.dart"
    required_inputs:
      - angel3_serialize.g.part
      - angel3_serialize_serializer.g.part
    applies_builders:
      - angel3_serialize_generator|angel3_serialize
      - source_gen|combining_builder
      - source_gen|part_cleanup"
