name: angel3_orm_generator
version: 7.2.0-beta.1
description: Code generators for Angel3 ORM. Generates query builder classes.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_generator
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_model: ^7.0.0
  angel3_serialize: ^7.0.0
  angel3_orm: ^7.0.0
  angel3_serialize_generator: ^7.2.0-beta.1
  analyzer: ^5.3.0
  inflection3: ^0.5.3+1
  build: ^2.0.1
  build_config: ^1.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  collection: ^1.15.0
  logging: ^1.0.0
  optional: ^6.0.0
dev_dependencies:
  angel3_framework: ^7.0.0
  angel3_migration: ^7.0.0
  build_runner: ^2.0.1
  postgres: ^2.4.0
  test: ^1.21.0
  lints: ^2.0.0
#dependency_overrides:
#   angel3_container:
#     path: ../../container/angel_container
#   angel3_framework:
#     path: ../../framework
#   angel3_http_exception:
#     path: ../../http_exception
#   angel3_model:
#     path: ../../model
#   angel3_route:
#     path: ../../route
#   angel3_mock_request:
#     path: ../../mock_request
#  angel3_serialize:
#    path: ../../serialize/angel_serialize
#  angel3_serialize_generator:
#    path: ../../serialize/angel_serialize_generator
#   angel3_orm:
#     path: ../angel_orm
#   angel3_migration:
#     path: ../angel_migration
 