name: jael3_preprocessor
version: 7.0.0
description: A pre-processor for resolving blocks and includes within Jael templates.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/jael/jael_preprocessor
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  file: ^6.1.0
  jael3: ^7.0.0
  belatuk_symbol_table: ^4.0.0
  collection: ^1.15.0
dev_dependencies:
  belatuk_code_buffer: ^4.0.0
  test: ^1.21.0
  lints: ^2.0.0
# dependency_overrides:
#   jael3:
#     path: ../jael
