name: angel3_shelf
version: 7.0.0-beta.2
description: Shelf interop with Angel3. Use this to wrap existing server code.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/shelf
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_framework: ^7.0.0
  angel3_container: ^7.0.0
  angel3_mock_request: ^7.0.0
  path: ^1.8.0
  shelf: ^1.3.0
  stream_channel: ^2.1.0
  logging: ^1.0.0
  charcode: ^1.3.0
  http: ^0.13.0
dev_dependencies: 
  angel3_test: ^7.0.0
  belatuk_pretty_logging: ^5.0.0
  shelf_static: ^1.1.0
  test: ^1.21.0
  lints: ^2.0.0
# dependency_overrides:
#   angel3_test:
#     path: ../test
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth 
#   angel3_client:
#     path: ../client
#   angel3_websocket:
#     path: ../websocket
#   angel3_validate:
#     path: ../validate
